builds:
  yshaarj-da:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIINOQAAAAAAAAAAAAAkkIpEhU0SSSSBSgSakEJSkQEkINpFSCA # DA_cthun_yshaarj_216978857336255_AoE
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIINOQAAAAAAAAAAAAAkkIpEhU0SSSSBSgSakEJSkQEkINpFSCA # DA_cthun_yshaarj_216978857336255_AoE
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIINOQAAAAAAAAAAAAAkIJpEhU0SSkUSIBKpRSkIRCRQi0kWIJAA # DA_yshaarj_cthun_216978847948479_ST
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEokGJRiEJEBJSTahkAA # DA_yshaarj_yogg_370843904366271_ST
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAIIIBAAAAAAAAAAAAQSIpEhU0SSSShDIBKpRSkIRCRQi0kWIJAA # DA_cthun_yshaarj_234566815521215_AoE
  yshaarj-yogg-vf:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgkIHoEh00SSSSBSgSakEJSkQEkINpFSCA # VF_yshaarj_yogg_370910485224895_AoE
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgkIHoEh00SSSSBSgSakEJSkQEkINpFSCA # VF_yshaarj_yogg_370910485224895_AoE
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJNtIRSJhEokGJRiEJEBJSTahkAA # VF_yshaarj_yogg_370843904366271_ST
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgIJKRINtkkkUISgSakEJSkQEkINpFSCA # VF_yshaarj_yogg_370842360323519_AoE
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAIigEAAAAAAAAAAAAASIpEh00SSSShDIBKpRSkIRCRQi0kWIJAA # VF_yshaarj_yogg_375304303876543_AoE
  cthun-yogg-vf:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDkIpEh00SSSSBSgSakEJSkQEkINpFSCA # VF_cthun_yogg_444577764285887_AoE
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAgIIBAAAAAAAAAAAAQSikSESTLJJJFIBKpRSkIRCRQi0kWIJAA # VF_cthun_yogg_445672980946367_AoE
    single: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDkIpEh00SSSSBSgSakEJSkQEkINpFSCA # VF_cthun_yogg_444577764285887_AoE
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDIJpEh00SSSShDIBKpRSkIRCRQi0kWIJAA # VF_cthun_yogg_444577821990335_AoE
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAgIIBAAAAAAAAAAAAQSIpEh00SSSShDIBKpRSkIRCRQi0kWIJAA # VF_cthun_yogg_445673048054207_AoE
gear:
  head: "draconic_hierophants_archcowl,id=200327,ilevel=424"
  neck: "alcs_pendant_of_fiery_dreams,id=109957,ilevel=421"
  shoulders: "draconic_hierophants_wisdom,id=200329,ilevel=424"
  back: "fireproof_drape,id=193763,ilevel=421"
  chest: "arcanists_resonant_robes,id=134415,ilevel=421"
  wrists: "felflame_bracers,id=109881,ilevel=421"
  hands: "draconic_hierophants_grips,id=200326,ilevel=415"
  waist: "sky_saddle_cord,id=193691,ilevel=421"
  legs: "draconic_hierophants_britches,id=200328,ilevel=415"
  feet: "sandals_of_the_wild_sovereign,id=195532,ilevel=424"
  finger1: "seal_of_filial_duty,id=195526,ilevel=430"
  finger2: "darkflame_loop,id=109766,ilevel=421"
  trinket1: "crimson_aspirants_badge_of_ferocity,id=201449,bonus_id=8989/8990/1498/8766,ilevel=392"
  trinket2: "crimson_aspirants_insignia_of_alacrity,id=201451,bonus_id=8989/8990/1498/8766,ilevel=392"
  main_hand: "final_grade,id=193707,ilevel=421"
  off_hand: ""
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character"
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only"
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims food and rune consumables you can use to augment your character"
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 385
      - 400
      - 415
    files:
      - enchants.simc
  gear:
    description: "NYI"
    builds: true
    weights: false
    chart: false
    lookupType: item
    steps:
      - 226
      - 233
    files:
      - t26.simc
  gems:
    description: "Sims all available gems against each other."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 385
      - 400
      - 415
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial for a particular actor that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims a lot of talent builds."
    iterations: smart
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - VF-ST.simc
      - VF-AoE.simc
      - DA-ST.simc
      - DA-AoE.simc
  tiersets:
    description: "Sims each tier set currently available by just activating the set, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 350
      - 366
      - 376
      - 379
      - 382
      - 385
      - 389
      - 392
      - 395
      - 398
      - 402
      - 405
      - 408
      - 411
      - 415
      - 418
      - 421
      - 424
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for BiS Mythic Sanctum of Domination gear.
    builds: true
    weights: true
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsVaultOfTheIncarnates
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
fourTargetWeights: weightsFourTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 10
  retryInterval: 2
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 1600
  steps: 700
  total: 10000
  include:
    - mastery
    - haste
    - crit
    - versatility
