builds:
  yshaarj-yogg-da:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEokGJJJSkQAJSTahEAA
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEokGJJJSkQAJSTahEAA
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEokGJJJSkQAJSTahEAA
  # no mental decay because of bug
  # mental decay version: BIQAAAAAAAAAAAAAAAAAAAAAAIItQAAAAAAAAAAAAAkIJpEpJFtDkEJlESgSakkkIRCBkINpFSAA
  yshaarj-cthun-da:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEokGJJJSkQAJSTahEAA
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEokGJJJSkQAJSTahEAA
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEokGJJJSkQAJSTahEAA
  yshaarj-yogg-vf:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJNtIRSJhEokGJJJSkQAJSTahEAA
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJNtIRSJhEokGJJJSkQAJSTahEAA
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJNtIRSJhEokGJJJSkQAJSTahEAA
gear:
  head: "draconic_hierophants_archcowl,id=200327,bonus_id=1463/8767,ilevel=392"
  neck: "elemental_lariat,id=193001,bonus_id=8836/8840/8902/8960/8784/8782/8802/8793,ilevel=392,gem_id=192955/192955/192955,crafted_stats=36/32"
  shoulders: "draconic_hierophants_wisdom,id=200329,bonus_id=1463/8767,ilevel=392"
  back: "vibrant_wildercloth_shawl,id=193511,bonus_id=8836/8840/8902/8801/8793,ilevel=392,enchant_id=6592,crafted_stats=40/32"
  chest: "draconic_hierophants_vestment,id=200324,bonus_id=1466/8767,ilevel=392,enchant_id=6625"
  wrists: "vibrant_wildercloth_wristwraps,id=193510,bonus_id=8836/8840/8902/8801/8793,ilevel=392,enchant_id=6574,crafted_stats=40/36"
  hands: "draconic_hierophants_grips,id=200326,bonus_id=1466/8767,ilevel=392"
  waist: "vibrant_wildercloth_girdle,id=193516,bonus_id=8836/8840/8902/8801/8793,ilevel=392,crafted_stats=36/40"
  legs: "vibrant_wildercloth_slacks,id=193518,bonus_id=8836/8840/8902/8801/8793,ilevel=392,enchant_id=6541,crafted_stats=36/32"
  feet: "vibrant_wildercloth_slippers,id=193519,bonus_id=8836/8840/8902/8802/8793,ilevel=392,enchant_id=6613,crafted_stats=36/49"
  finger1: "ringbound_hourglass,id=193000,bonus_id=8836/8840/8902/8780/8802/8793,ilevel=392,gem_id=192955,crafted_stats=40/32"
  finger2: "signet_of_titanic_insight,id=192999,bonus_id=8836/8840/8902/8780/8802/8793,ilevel=392,gem_id=192955,enchant_id=6556,crafted_stats=36/40"
  trinket1: "crimson_aspirants_badge_of_ferocity,id=201449,bonus_id=8989/8990/1498/8766,ilevel=392"
  trinket2: "crimson_aspirants_insignia_of_alacrity,id=201451,bonus_id=8989/8990/1498/8766,ilevel=392"
  main_hand: "illuminating_pillar_of_the_isles,id=194898,bonus_id=8836/8840/8902/8802/8793,ilevel=392,enchant_id=6643,crafted_stats=49/36"
  off_hand: ""
sims:
  apl:
    description: "APL Sims used for testing rotational changes only"
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims all consumables you can use to augment your character"
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - enchants.simc
  gear:
    description: "NYI"
    builds: true
    weights: false
    chart: false
    lookupType: item
    steps:
      - 226
      - 233
    files:
      - t26.simc
  racials:
    description: "Swaps out the racial for a particular actor that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims a lot of talent builds."
    iterations: smart
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - VF-ST.simc
      - VF-AoE.simc
      - DA-ST.simc
      - DA-AoE.simc
  tiersets:
    description: "Sims each tier set currently available by just activating the set, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 350
      - 366
      - 372
      - 376
      - 379
      - 382
      - 385
      - 389
      - 392
      - 395
      - 398
      - 402
      - 405
      - 408
      - 411
      - 415
      - 418
      - 421
      - 424
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for BiS Mythic Sanctum of Domination gear.
    builds: true
    weights: true
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsSepulcherOfTheFirstOnes
singleTargetWeights: weightsSingle
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 10
  retryInterval: 2
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 1600
  steps: 700
  total: 10000
  include:
    - mastery
    - haste
    - crit
    - versatility
