builds:
  yogg-da:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEgGCJgAAQkEAA # DA_370843904366271_ST (yshaarj-yogg)
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtDIJJlESAaIkACAARSAA # DA_370843635931071_ST (yshaarj-yogg)
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEgGCJgAAQkEAA # DA_370843904366271_ST (yshaarj-yogg)
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJFtIRSJhEgGCJgAAQkEAA # DA_370843904366271_ST (yshaarj-yogg)
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAgIIBAAAAAAAAAAAAQSikSESRTSSShIBohQCIAAEJBAA # DA_445673299713471_AoE (cthun-yogg)
  yshaarj-yogg-vf:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJNtDIJJlESAaIkACAARSAA # VF_370843635931071_ST
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0cgEAAAAAAAAAAAAAikoEh00SSSSJIBohQCIAAEJBAA # VF_371391512158143_ST
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJNtIRSJhEgGCJgAAQkEAA # VF_370843904366271_ST
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIi0cgEAAAAAAAAAAAAASioEh00kkkUISAaIkACAARSAA # VF_371391840329151_AoE
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgkIHoEh00kkkUISAaIkACAARSAA # VF_370910803991999_AoE
  cthun-yogg-vf:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDIJpEh00SSSSJIBohQCIAAEJBAA # VF_444577754881983_ST
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAgIIBAAAAAAAAAAAAQikkSESTLJJJlgEgGCJgAAQkEAA # VF_445672971542463_ST
    single: BIQAAAAAAAAAAAAAAAAAAAAAAgItIBAAAAAAAAAAAAQIJpEpJNtIRSJhEgGCJgAAQkEAA # VF_444562723034815_ST
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDkIpEh00kkkUISAaIkACAARSAA # VF_444578083052991_AoE
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAgIIBAAAAAAAAAAAAQSikSESTTSSShIBohQCIAAEJBAA # VF_445673299713471_AoE
gear:
  head: "head=draconic_hierophants_archcowl,id=200327,ilevel=424"
  neck: "neck=alcs_pendant_of_fiery_dreams,id=109957,ilevel=418"
  shoulders: "shoulder=draconic_hierophants_wisdom,id=200329,ilevel=424"
  back: "back=fireproof_drape,id=193763,ilevel=418"
  chest: "chest=arcanists_resonant_robes,id=134415,ilevel=418"
  wrists: "wrists=felflame_bracers,id=109881,ilevel=418"
  hands: "hands=draconic_hierophants_grips,id=200326,ilevel=415"
  waist: "waist=sky_saddle_cord,id=193691,ilevel=418"
  legs: "legs=draconic_hierophants_britches,id=200328,ilevel=415"
  feet: "feet=sandals_of_the_wild_sovereign,id=195532,ilevel=424"
  finger1: "finger1=seal_of_filial_duty,id=195526,ilevel=430"
  finger2: "finger2=darkflame_loop,id=109766,ilevel=418"
  trinket1: "crimson_aspirants_badge_of_ferocity,id=201449,bonus_id=8989/8990/1498/8766,ilevel=392"
  trinket2: "crimson_aspirants_insignia_of_alacrity,id=201451,bonus_id=8989/8990/1498/8766,ilevel=392"
  main_hand: "main_hand=final_grade,id=193707,ilevel=418"
  off_hand: ""
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character"
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only"
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims food and rune consumables you can use to augment your character"
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 385
      - 400
      - 415
    files:
      - enchants.simc
  gear:
    description: "NYI"
    builds: true
    weights: false
    chart: false
    lookupType: item
    steps:
      - 226
      - 233
    files:
      - t26.simc
  gems:
    description: "Sims all available gems against each other."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 385
      - 400
      - 415
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial for a particular actor that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims a lot of talent builds."
    iterations: smart
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - VF-ST.simc
      - VF-AoE.simc
      - DA-ST.simc
      - DA-AoE.simc
  tiersets:
    description: "Sims each tier set currently available by just activating the set, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 350
      - 366
      - 376
      - 379
      - 382
      - 385
      - 389
      - 392
      - 395
      - 398
      - 402
      - 405
      - 408
      - 411
      - 415
      - 418
      - 421
      - 424
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for BiS Mythic Sanctum of Domination gear.
    builds: true
    weights: true
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsVaultOfTheIncarnates
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
fourTargetWeights: weightsFourTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 10
  retryInterval: 2
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 1600
  steps: 700
  total: 10000
  include:
    - mastery
    - haste
    - crit
    - versatility
